Push images to Docker Hub

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -32,12 +32,31 @@ script:
         DOCKER_TAG="latest"
       fi
       docker build -t demo-site:$DOCKER_TAG -f $DOCKERFILE .
-      DOCKER_RESULT=$?
-      if [ "$DOCKER_RESULT" -ne "0" ]; then
-        exit $DOCKER_RESULT
+      if [ "$?" -ne "0" ]; then
+        echo "Docker build failed: $DOCKER_TAG"
+        exit 1
       fi
     done
 after_success:
+  # push docker image
+  - >
+    docker login -u="rycus86" -p="$DOCKER_PASSWORD"
+    if [ "$?" -ne "0" ]; then
+      echo "Failed to log in to Docker Hub"
+      exit 1
+    fi
+    for DOCKERFILE in Dockerfile*; do
+      DOCKER_TAG=$(echo "$DOCKERFILE" | sed 's/Dockerfile\.*//g')
+      if [ -z "$DOCKER_TAG" ]; then
+      docker tag demo-site:$DOCKER_TAG rycus86/demo-site:$DOCKER_TAG
+      docker push rycus86/demo-site:$DOCKER_TAG
+      if [ "$?" -ne "0" ]; then
+        echo "Failed to push docker image for $DOCKER_TAG"
+        exit 1
+      fi
+    else
+      echo 'Not pushing to Docker Hub'
+    fi
   # coverage reports
   - coveralls
   - python -m coverage report -m
